import Car_1 from "../public/images/car_1.jpg";
import Car_2 from "../public/images/car_2.jpg";
import Car_3 from "../public/images/car_3.jpg";
import Car_4 from "../public/images/car_4.jpg";
import Car_5 from "../public/images/car_5.jpg";
import Car_6 from "../public/images/car_6.jpg";
import Car_7 from "../public/images/car_7.jpg";
import Car_8 from "../public/images/car_8.jpg";

export const carItems = [
  {
    name: "Koenigsegg",
    category: "Sport",
    category_fa: "اسپورت",
    gas: "90L",
    gas_fa: "90 لیتر",
    gear: "Manual",
    gear_fa: "دستی",
    passengers: "2 People",
    passengers_fa: "2 نفر",
    final_price: 107,
    img: Car_1,
    is_like: false,
    rating : 4 ,
    id: 1,
  },
  {
    name: "Nissan GT - R",
    category: "Sport",
    category_fa: "اسپورت",
    gas: "80L",
    gas_fa: "80 لیتر",
    gear: "Manual",
    gear_fa: "دستی",
    passengers: "4 People",
    passengers_fa: "4 نفر",
    final_price: 80,
    off_price: 100,
    img: Car_2,
    is_like: false,
    rating : 5 ,
    id: 2,
  },
  {
    name: "Rolls - Royce",
    category: "Sedan",
    category_fa: "سدان",
    gas: "70L",
    gas_fa: "70 لیتر",
    gear: "Manual",
    gear_fa: "دستی",
    passengers: "4 People",
    passengers_fa: "4 نفر",
    final_price: 96,
    img: Car_3,
    is_like: false,
    rating : 3 ,
    id: 3,
  },
  {
    name: "All New Rush",
    category: "SUV",
    category_fa: "اس یو وی",
    gas: "70L",
    gas_fa: "70 لیتر",
    gear: "automatic",
    gear_fa: "اتومات",
    passengers: "6 People",
    passengers_fa: "6 نفر",
    final_price: 72,
    off_price: 80,
    img: Car_4,
    is_like: false,
    rating : 5 ,
    id: 4,
  },
  {
    name: "CR  - V",
    category: "SUV",
    category_fa: "اس یو وی",
    gas: "80L",
    gas_fa: "80 لیتر",
    gear: "Manual",
    gear_fa: "دستی",
    passengers: "6 People",
    passengers_fa: "6 نفر",
    final_price: 80,
    img: Car_5,
    is_like: false,
    rating : 3 ,
    id: 5,
  },
  {
    name: "All New Terios",
    category: "SUV",
    category_fa: "اس یو وی",
    gas: "90L",
    gas_fa: "90 لیتر",
    gear: "Manual",
    gear_fa: "دستی",
    passengers: "6 People",
    passengers_fa: "6 نفر",
    final_price: 94,
    img: Car_6,
    is_like: false,
    rating : 4 ,
    id: 6,
  },
  {
    name: "MG ZX Excite",
    category: "Hatchback",
    category_fa: "هاچ بک",
    gas: "60L",
    gas_fa: "60 لیتر",
    gear: "Manual",
    gear_fa: "دستی",
    passengers: "6 People",
    passengers_fa: "6 نفر",
    final_price: 74,
    img: Car_7,
    is_like: false,
    rating : 2 ,
    id: 7,
  },
  {
    name: "New MG ZS",
    category: "SUV",
    category: "اس یو وی",
    gas: "80L",
    gas: "80 لیتر",
    gear: "automatic",
    gear: "اتومات",
    passengers: "2 People",
    passengers: "2 نفر",
    final_price: 87,
    off_price: 94,
    img: Car_8,
    is_like: false,
    rating : 5 ,
    id: 8,
  },
];
