import Car_1 from "../public/images/car_1.jpg";
import Car_2 from "../public/images/car_2.jpg";
import Car_3 from "../public/images/car_3.jpg";
import Car_4 from "../public/images/car_4.jpg";
import Car_5 from "../public/images/car_5.jpg";
import Car_6 from "../public/images/car_6.jpg";
import Car_7 from "../public/images/car_7.jpg";
import Car_8 from "../public/images/car_8.jpg";

export const carItems = [
  {
    name: "Koenigsegg",
    category: "Sport",
    gas: "90L",
    gear: "Manual",
    passengers: "2 People",
    final_price: "107.00",
    img: Car_1,
    is_like: false,
    rating : 4 ,
    id: 1,
  },
  {
    name: "Nissan GT - R",
    category: "Sport",
    gas: "80L",
    gear: "Manual",
    passengers: "4 People",
    final_price: "80.00",
    off_price: "100.00",
    img: Car_2,
    is_like: false,
    rating : 5 ,
    id: 2,
  },
  {
    name: "Rolls - Royce",
    category: "Sedan",
    gas: "70L",
    gear: "Manual",
    passengers: "4 People",
    final_price: "96.00",
    img: Car_3,
    is_like: false,
    rating : 3 ,
    id: 3,
  },
  {
    name: "All New Rush",
    category: "SUV",
    gas: "70L",
    gear: "Manual",
    passengers: "6 People",
    final_price: "72.00",
    off_price: "80.00",
    img: Car_4,
    is_like: false,
    rating : 5 ,
    id: 4,
  },
  {
    name: "CR  - V",
    category: "SUV",
    gas: "80L",
    gear: "Manual",
    passengers: "6 People",
    final_price: "80.00",
    img: Car_5,
    is_like: false,
    rating : 3 ,
    id: 5,
  },
  {
    name: "All New Terios",
    category: "SUV",
    gas: "90L",
    gear: "Manual",
    passengers: "6 People",
    final_price: "94.00",
    img: Car_6,
    is_like: false,
    rating : 4 ,
    id: 6,
  },
  {
    name: "MG ZX Excite",
    category: "Hatchback",
    gas: "60L",
    gear: "Manual",
    passengers: "6 People",
    final_price: "74.00",
    img: Car_7,
    is_like: false,
    rating : 2 ,
    id: 7,
  },
  {
    name: "New MG ZS",
    category: "SUV",
    gas: "80L",
    gear: "Manual",
    passengers: "2 People",
    final_price: "87.00",
    off_price: "94.00",
    img: Car_8,
    is_like: false,
    rating : 5 ,
    id: 8,
  },
];
