export const carItems = [
  {
    name: "Koenigsegg",
    category: "Sport",
    gas: "90L",
    gear: "Manual",
    passengers: "2 People",
    final_price: "99.00",
    is_like: true,
    id: 1,
  },
  {
    name: "Nissan GT - R",
    category: "Sport",
    gas: "80L",
    gear: "Manual",
    passengers: "4 People",
    final_price: "80.00",
    off_price: "100.00",
    is_like: false,
    id: 2,
  },
  {
    name: "Rolls - Royce",
    category: "Sedan",
    gas: "70L",
    gear: "Manual",
    passengers: "4 People",
    final_price: "96.00",
    is_like: true,
    id: 3,
  },
  {
    name: "All New Rush",
    category: "SUV",
    gas: "70L",
    gear: "Manual",
    passengers: "6 People",
    final_price: "72.00",
    off_price: "80.00",
    is_like: false,
    id: 4,
  },
  {
    name: "CR  - V",
    category: "SUV",
    gas: "80L",
    gear: "Manual",
    passengers: "6 People",
    final_price: "80.00",
    is_like: true,
    id: 5,
  },
  {
    name: "All New Terios",
    category: "SUV",
    gas: "90L",
    gear: "Manual",
    passengers: "6 People",
    final_price: "94.00",
    is_like: false,
    id: 6,
  },
  {
    name: "MG ZX Excite",
    category: "Hatchback",
    gas: "60L",
    gear: "Manual",
    passengers: "6 People",
    final_price: "74.00",
    is_like: false,
    id: 7,
  },
  {
    name: "New MG ZS",
    category: "SUV",
    gas: "80L",
    gear: "Manual",
    passengers: "2 People",
    final_price: "94.00",
    off_price: "87.00",
    is_like: true,
    id: 8,
  },
];
