import Head from 'next/head'
import Image from 'next/image'
import BannerHome from '../components/BannerHome'
import SearchCar from '../components/SearchCar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    < >
      <Head>
        <title>Rent Car Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BannerHome />
      <SearchCar />
      
    </>
  )
}
