import Head from "next/head";
import Image from "next/image";
import BannerHome from "../components/BannerHome";
import CarCart from "../components/CarCart";
import SearchCar from "../components/SearchCar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Rent Car Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BannerHome />
      <SearchCar />
      <div className="container mx-auto xl:max-w-screen-2xl grid gap-8 grid-cols-1 md:grid-cols-2 lg:grid-cols-4 pt-4">
        <CarCart />
      </div>
    </>
  );
}
